### ISSUE TITLE
`malformed version`

### ISSUE THREAD

**Issue by closetool** [ent/ent#1552]
When I use `ent` connecting postgres, I encountered an error `panic: sql/schema: malformed version: 90602`

- [x] I have searched the [issues](https://github.com/facebook/ent/issues) of this repository and believe that this is not a duplicate.
- [x] The issue is present in the latest release.

## Current Behavior 😯

Received an error `sql/schema: malformed version: 90602`
It caused by https://github.com/ent/ent/blob/master/dialect/sql/schema/postgres.go#L44

## Expected Behavior 🤔

It shouldn't happen

## Steps to Reproduce 🕹

Just connect to postgres

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.16.3  |
| Ent         | 0.8.0   |
| Database    | postgres   |
| Driver      | github.com/lib/pq      |

And this is my docker compose file
```yml
version: '3'

services:
  mysql:
    restart: always
    image: mysql:5.7
    container_name: my_mysql
    environment:
      - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
        #- "MYSQL_ROOT_PASSWORD=123456"
      - "MYSQL_DATABASE=mydb"
      - "TZ=Asia/Shanghai"
    ports:
      - 3306:3306

  db:
    restart: always
    image: postgres:9.6.2
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: "postgres"
      PGDATA: /var/lib/postgresql/data/pgdata
```
