### ISSUE TITLE
integrate gqlgen federation got error "merging type systems failed: unable to bind to interface: role/ent.Role does not satisfy the interface github.com/99designs/gqlgen/plugin/federation/fedruntime.Entityexit status 1"

### ISSUE THREAD

**Issue by demobin8** [ent/ent#1620]
schema:
````
type Query {
    node(id: ID!): Node
    nodes(ids: [ID!]!): [Node]!
    roles(
        after: Cursor
        first: Int
        before: Cursor
        last: Int
        orderBy: RoleOrder
    ): RoleConnection
}

type Mutation {
    createRole(role: RoleInput!): Role!
}

interface Node {
    id: ID!
}

scalar Time

type Role implements Node @key(fields: "id") {
    id: ID!
    name: String!
    remark: String
}

input RoleInput {
    name: String!
    remark: String!
}

type RoleConnection {
    totalCount: Int!
    pageInfo: PageInfo!
    edges: [RoleEdge]
}

type RoleEdge {
    node: Role
    cursor: Cursor!
}

enum OrderDirection {
    ASC
    DESC
}

enum RoleOrderField {
    NAME
}

input RoleOrder {
    direction: OrderDirection!
    field: RoleOrderField
}

scalar Cursor

type PageInfo {
    hasNextPage: Boolean!
    hasPreviousPage: Boolean!
    startCursor: Cursor
    endCursor: Cursor
}
````
gqlgen.yml:
````
schema:
  - role.graphql

resolver:
  layout: follow-schema
  dir: .

autobind:
  - role/ent

models:
  ID:
    model:
      - github.com/99designs/gqlgen/graphql.IntID
  Node:
    model:
      - role/ent.Noder

federation:
  filename: federation.go
````
cmd:
`go run github.com/99designs/gqlgen generate --config gqlgen.yml`
error:
`merging type systems failed: unable to bind to interface: role/ent.Role does not satisfy the interface github.com/99designs/gqlgen/plugin/federation/fedruntime.Entityexit status 1`
