### ISSUE TITLE
entgql node.tmp not support int32 below node id

### ISSUE THREAD

**Issue by tsingsun** [ent/ent#2241]
Code segment at [github.com/ent/contrib/blob/master/entgql/template/node.tmp](https://github.com/ent/contrib/blob/dcb3272c6a7adbacec3aa566a6832d6b3ef0410a/entgql/template/node.tmpl#L304)
```
idx := int(id/(1<<32 - 1))
```
if parameter `id` is int32,this statement cause error: Invalid operation: id / (1<<32 - 1) (cannot convert the constant (1<<32 - 1) to the type int32)

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

entgql node.tmp not support int32 below node id

## Expected Behavior 🤔

node id support all kind of int type
## Steps to Reproduce 🕹

Steps:

1. gqlgem.yml config
```
models:
  # Defines the ID field as Go 'int'.
  ID:
    model:
      - github.com/99designs/gqlgen/graphql.ID
      - github.com/99designs/gqlgen/graphql.Int32
```
2. generate with entgql

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.17.3  |
| Ent         | 0.9.2   |
| Database    | MySQL   |
| Driver      | https://github.com/go-sql-driver/mysql        |
