### ISSUE TITLE
entgql: Add support for Bytes fields

### ISSUE THREAD

**Issue by scraymondjr** [ent/ent#2516]
entgql currently fails to generate `Bytes` fields with error message `"bytes type not implemented"`.

- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

Suggest following idea outlined in gqlgen issue https://github.com/99designs/gqlgen/issues/597.

If a `Bytes` field exists in the ent schema, then 
1. Inject `scalar Bytes` in the graphql schema
2. Add the following marshaling code to the generated ent files:
```
func MarshalBytes(b []byte) graphql.Marshaler {
	return graphql.WriterFunc(func(w io.Writer) {
		_, _ = fmt.Fprintf(w, "%q", string(b))
	})
}

func UnmarshalBytes(v interface{}) ([]byte, error) {
	switch v := v.(type) {
	case string:
		return []byte(v), nil
	case *string:
		return []byte(*v), nil
	case []byte:
		return v, nil
	default:
		return nil, fmt.Errorf("%T is not []byte", v)
	}
}
```

## Motivation 🔦

Ideally, all ent field types are able to be mapped to a graphql schema. This addition would allow for ent `Bytes` fields to be seamlessly added to generated graphql schemas.

**Comment by giautm** [comment]
Hey @scraymondjr, thank you for reporting the issue.

However, I think the `[]byte` should implement by the application on its side rather Ent. Because the byte array usually contains binary data and may be formatted in many variants of the form: base64, hex, string... So, there is no simple way to implement it in ent.

**Comment by scraymondjr** [comment]
Could you provide an example of what you expect consumers of Ent to do to enable Bytes Ent field in their graphql schema?

I'm also confused by the reason to not support this. If the raw data format is being stored as `[]byte`, then why does the encoding matter? Further, would it not make sense to have a sensible default way of handling Bytes fields and allow for enabling/disabling or other configuration of this option to meet the goal specified in the Motivation section of "all ent field types are able to be mapped to a graphql schema"?

**Comment by giautm** [comment]
Thank you for asking the question.

There are some answers:
- If the user expect the []byte to be visible as a string, why they are not using a string field instead?
- If we provide a default way for []byte like JSON did - as a base64. Then someone disagree to use that format, how we make it more customize?
- For very special use case I suggest the application should create its own scalar type and mapping it to entgql via entgql.Type('RawPayload')

**Comment by idc77** [comment]
The problem remains.

Instead of it "just working" some custom workaround have to be done (which?)
```
go generate ./...
failed to load schema: ent.graphql:9: Expected Name, found ]
exit status 1
generate.go:4: running "go": exit status 1
```

```yml
directive @goField(forceResolver: Boolean, name: String, omittable: Boolean) on FIELD_DEFINITION | INPUT_FIELD_DEFINITION
directive @goModel(model: String, models: [String!], forceGenerate: Boolean) on OBJECT | INPUT_OBJECT | SCALAR | ENUM | INTERFACE | UNION
"""
CreateCustomerInput is used for create Customer object.
Input was generated by ent.
"""
input CreateCustomerInput {
  username: String!
  secret: []byte!
  address: String
  sameAsInvoice: Boolean
  invoiceAddress: String
  isBusiness: Boolean
  vatID: String
  emailIDs: [ID!]
  limitIDs: [ID!]
  resellerID: ID
}
```
