### ISSUE TITLE
entgql: upgrade to contrib 0.3.4 broke my uuid field

### ISSUE THREAD

**Issue by advanderveer** [ent/ent#3277]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Given the following Go schema:
```Go
package schema

import (
	"time"

	"entgo.io/contrib/entgql"
	"entgo.io/ent"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/field"
	"entgo.io/ent/schema/index"
	"github.com/google/uuid"
)

// Profile schema
type Profile struct {
	ent.Schema
}

// Fields of the node.
func (s Profile) Fields() []ent.Field {
	return []ent.Field{
		field.UUID("username", uuid.UUID{}).Unique(),
		field.String("email").Optional(),
		field.String("phone_number").Optional(),
		field.Time("created_at").
			Default(time.Now).
			Immutable().
			Annotations(
				entgql.OrderField("CREATED_AT"),
			),
	}
}

// Indexes of the node.
func (Profile) Indexes() []ent.Index {
	return []ent.Index{
		index.Fields("created_at"),
	}
}

// Annotations of the node.
func (Profile) Annotations() []schema.Annotation {
	return []schema.Annotation{
		entgql.RelayConnection(),
		entgql.QueryField(),
	}
}
```

And the following graphql schema: 
```graphql
# support Go time time
scalar Time
# support UUID type
scalar UUID

# Mutations hold endpoints for changing data
type Mutation {
  initProfile(username: UUID!): Profile!
}
```
with the following gqlgen.yml
```yaml
schema:
  - schema/*.graphql
exec:
  filename: model/graph/generated.go
  package: graph
model:
  filename: model/models_gen.go
  package: model
autobind:
  - github.com/crewlinker/backend/model
models:
  ID:
    model:
      - github.com/99designs/gqlgen/graphql.IntID
  UUID:
    model:
      - github.com/crewlinker/backend/internal/clgql.UUID #custom uuid type, see blow
  Node:
    model:
      - github.com/crewlinker/backend/model.Noder
  Int:
    model:
      - github.com/99designs/gqlgen/graphql.Int
      - github.com/99designs/gqlgen/graphql.Int64
      - github.com/99designs/gqlgen/graphql.Int32
```

And custom uuid type ( github.com/crewlinker/backend/internal/clgql/uuid.go): 
```Go
package clgql

import (
	"fmt"
	"io"
	"strconv"

	"github.com/99designs/gqlgen/graphql"
	"github.com/google/uuid"
)

// MarshalUUID provides encoding for this type to the graphql layer
func MarshalUUID(u uuid.UUID) graphql.Marshaler {
	return graphql.WriterFunc(func(w io.Writer) {
		_, _ = io.WriteString(w, strconv.Quote(u.String()))
	})
}

// UnmarshalUUID provide decoding for the UUID type to the graphql layer
func UnmarshalUUID(v interface{}) (u uuid.UUID, err error) {
	s, ok := v.(string)
	if !ok {
		return u, fmt.Errorf("invalid type %T, expect string", v)
	}
	return uuid.Parse(s)
}
```

It generated the following graphql in version 0.3.3 of ent contrib
```graphql
# ....
type Profile implements Node {
  id: ID!
  username: UUID!
  email: String
  phoneNumber: String
  createdAt: Time!
}
# ....
```

but in 0.3.4 it generates:
```graphql
type Profile implements Node {
  id: ID!
  username: [UUID!]! #<- this got changed to an array, breaking my resolver code
  email: String
  phoneNumber: String
  createdAt: Time!
}
```

## Expected Behavior 🤔

It should generate graphql field for my UUID type in the same way as version 0.3.3

## Steps to Reproduce 🕹

I can't provide it right now but if the issue doesn't turn out to be obvious I can provide one.

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.19.5  |
| Ent         |  v0.11.7   |
| Database    | Postgres   |
| Driver      | pgx        |
