### ISSUE TITLE
Generated graphql schema contains unknow type "UUID"

### ISSUE THREAD

**Issue by detaribalazs** [ent/ent#3283]
Hi! I'm new to ent's GraphQL integration and wanted to try it out with a simple application, but I'm unable to generate the required code, because it fails with  `Unknown type "UUID"`.

My schema definition looks like this

```go
// database/ent/schema/item.go

import (
	"entgo.io/contrib/entgql"
	"entgo.io/ent"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

type Item struct {
	ent.Schema
}

func (Item) Fields() []ent.Field {
	return []ent.Field{
		field.UUID("sku", uuid.UUID{}).Default(uuid.New),
		field.String("name"),
		field.Int("price").Positive(),
	}
}

func (Item) Edges() []ent.Edge {
	return []ent.Edge{
		edge.From("tags", Tag.Type).Ref("items"),
	}
}

func (Item) Annotations() []schema.Annotation {
	return []schema.Annotation{
		entgql.RelayConnection(),
		entgql.QueryField(),
	}
}
```

I want to marshal/unmarshal the UUID field with the same code as in todo example:

```go
// gql/uuidgql/uuidgql.go

package uuidgql

import (
	"fmt"
	"io"
	"strconv"

	"github.com/99designs/gqlgen/graphql"
	"github.com/google/uuid"
)

func MarshalUUID(u uuid.UUID) graphql.Marshaler {
	return graphql.WriterFunc(func(w io.Writer) {
		_, _ = io.WriteString(w, strconv.Quote(u.String()))
	})
}

func UnmarshalUUID(v interface{}) (u uuid.UUID, err error) {
	s, ok := v.(string)
	if !ok {
		return u, fmt.Errorf("invalid type %T, expect string", v)
	}
	return uuid.Parse(s)
}
```

I've created the `entc.go` file with the following content:

```go
// database/ent/entc.go

func main() {
	log.Println("Starting generating based on schemas in ./schema directory with GraphQL extension")
	ex, err := entgql.NewExtension(
		entgql.WithSchemaGenerator(),
		entgql.WithWhereInputs(true),
		entgql.WithSchemaPath("ent.graphql"),
		entgql.WithConfigPath("gqlgen.yml"),
	)
	if err != nil {
		log.Fatalf("creating entgql extension: %v", err)
	}
	if err := entc.Generate("./schema", &gen.Config{Target: "./generated"}, entc.Extensions(ex)); err != nil {
		log.Fatalf("running ent codegen: %v", err)
	}
	log.Println("Finished generating code for ent")
}
```

and `gqlgen.yml`:

```yaml
# database/ent/gqlgen.yml

schema:
  - ./ent.graphql

resolver:
  layout: follow-schema
  dir: ../../gql

autobind:
  - github.com/detaribalazs/gqlsample/database/ent
  - github.com/detaribalazs/gqlsampledatabase/ent/item
  - github.com/detaribalazs/gqlsample/database/ent/tag

models:
  ID:
    model:
      - github.com/99designs/gqlgen/graphql.IntID
  UUID:
    model:
      - github.com/detaribalazs/gqlsample/gql/uuidgql.UUID
  Node:
    model:
      - github.com/detaribalazs/gqlsample/database/ent/generated.Noder
  Time:
    model:
      - github.com/99designs/gqlgen/graphql.Time
```

When I try to run `go generate` with the following `generate.go`:

```go
// database/ent/generate.go

package ent

//go:generate go run -mod=mod entc.go
//go:generate go run -mod=mod github.com/99designs/gqlgen
```
I get the following output:

```bash
$ go generate
2023/01/28 21:35:11 Starting generating based on schemas in ./schema directory with GraphQL extension
2023/01/28 21:35:14 Finished generating code for ent
failed to load schema: ./ent.graphql:10: Undefined type UUID.
exit status 1
generate.go:4: running "go": exit status 1
```

The `Item` type in the generated GraphQL file is the following, with `Unknown type "UUID"`:

```graphql
type Item implements Node {
  id: ID!
  sku: [UUID!]!
  name: String!
  price: Int!
  tags: [Tag!]
}
```

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          |  go1.19 linux/amd64  |
| Ent         | v0.11.7   |
| gqlgen  | v0.17.22 |
| Database    | NA   |
| Driver      | NA  |

Is this the expected behavior? If yes, how could I make it work?

**Comment by crossworth** [comment]
Hi @detaribalazs, I want to point two things, the first is that you should define the [scalar type](https://gqlgen.com/reference/scalars/):

On the GraphQL schema:
```graphql
scalar UUID
```

The second thing, is that you should update the `entgql` to master, to fix the problem where the `sku` is an array.
More info on this issue:
https://github.com/ent/ent/issues/3277

To update to master:
```
go get entgo.io/contrib@master
```

Please, give a try and if you still have problems, let me know.

**Comment by detaribalazs** [comment]
Hi @crossworth, thanks for the super quick reply! After upgrading to master, the generated SKU is not defined as array anymore, but I still see the initial problem. My expectation was that the [scalar type definition](https://gqlgen.com/reference/scalars/#custom-scalars-with-third-party-types) is taken care by the following line in the `gqlgen.yml` file:

```yaml
UUID:
    model:
      - github.com/detaribalazs/gqlsample/gql/uuidgql.UUID
```
