### ISSUE TITLE
Problems with gqlgen.yml during GraphQL integration

### ISSUE THREAD

**Issue by ji21** [ent/ent#3402]
Hello, I am running into this error in the autobind field of the gqlgen.yml file:

1) generating core failed: unable to load github.com/username/project/server/src/api/ent - make sure you're using an import path to a package that exists

and this error when defining the Node model in gqlgen.yml:

2) panic: unable to find type: github.com/username/project/server/src/api/ent.Noder

When running go generate generate.go.

Here's gqlgen.yml:
```
# schema tells gqlgen where the GraphQL schema is located.
schema:
  - ./graphQL/ent.graphql

# resolver reports where the resolver implementations go.
resolver:
  layout: follow-schema
  dir: ./graphQL

# gqlgen will search for any type names in the schema in these go packages
# if they match it will use them, otherwise it will generate them.

# autobind tells gqngen to search for any type names in the GraphQL schema in the
# provided package. If they match it will use them, otherwise it will generate new.
autobind:
  - github.com/username/project/server/src/api/ent

# This section declares type mapping between the GraphQL and Go type systems.
models:
  # Defines the ID field as Go 'int'.
  ID:
    model:
      - github.com/99designs/gqlgen/graphql.IntID
  Node:
    model:
      - github.com/username/project/server/src/api/ent.Noder
  JSON:
    model:
      - github.com/99designs/gqlgen/graphql.Map
```

Here's generate.go:
```
package main

//go:generate go run -mod=mod ./graphQL/entc.go --target=./ent/entg
//go:generate go run -mod=mod github.com/99designs/gqlgen --config ./graphQL/gqlgen.yml

```

And here's where I found the ent.Noder model in the ent.graphql file:
```
interface Node @goModel(model: "github.com/username/project/server/src/api/ent.Noder") {
  """The id of the object."""
  id: ID!
}
```

I also attached a screenshot of my file structure, which I don't understand why I am not about to import the ent package correctly (module github.com/username/project/server/src/api)

<img width="770" alt="Screenshot 2023-03-21 at 7 33 40 PM 1" src="https://user-images.githubusercontent.com/61668297/226708033-636d1909-8495-43b5-a549-539362cf973e.png">

Lastly, here's my entc.go file:

```
//go:build ignore

package main

import (
	"flag"
	"log"

	"entgo.io/contrib/entgql"
	"entgo.io/ent/entc"
	"entgo.io/ent/entc/gen"
)

func main() {
	ex, err := entgql.NewExtension(
		// Tell Ent to generate a GraphQL schema for
		// the Ent schema in a file named ent.graphql.
		entgql.WithSchemaGenerator(),
		entgql.WithSchemaPath("graphQL/ent.graphql"),
		entgql.WithConfigPath("graphQL/gqlgen.yml"),
	)
	if err != nil {
		log.Fatalf("creating entgql extension: %v", err)
	}
	opts := []entc.Option{
		entc.Extensions(ex),
	}

	var target string
	flag.StringVar(&target, "target", "../../ent", "Target directory for the generated code")
	flag.Parse()

	if err := entc.Generate("./ent/schema", &gen.Config{
		Target: target,
	}, opts...); err != nil {
		log.Fatalf("running ent codegen: %v", err)
	}
}
```

I think I'm missing something, and I'm following this part of the documentation (https://entgo.io/docs/tutorial-todo-gql#basic-setup). Please could someone help me out? Thanks!
