### ISSUE TITLE
Support int32 with entgql and RelayConnections

### ISSUE THREAD

**Issue by tobikris** [ent/ent#4379]
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

I expected the following to work:

```yaml
# Use int32 (as GraphQL standard requires, but gqlgen does not by default).
models:
  ID:
    model:
      - github.com/99designs/gqlgen/graphql.Int32
  Int:
    model:
      - github.com/99designs/gqlgen/graphql.Int32
```

However, the generated resolvers are not compatible anymore.

```go
func (r *queryResolver) Devices(ctx context.Context, after *entgql.Cursor[int], first *int32, before *entgql.Cursor[int], last *int32, where *ent.DeviceWhereInput) (*ent.DeviceConnection, error) {
	return r.client.Device.Query().Paginate(ctx, after, first, before, last, ent.WithDeviceFilter(where.Filter))
}
```

as Paginate expects `*int`. I could do a type conversion here, but I was wondering if this should rather be fixed in the code generation.

## Motivation 🔦

I would like to be able to use int32 as the [GraphQL spec](https://spec.graphql.org/draft/#sec-Int) uses 32-bit integers explicitly. Maybe my intention is also caused by inaccurate understanding of the intentions of the gqlgen.yml and available types - please let me know if you think that is the case, thanks!
